// flow-typed signature: 3ba883a96a65f0c813982c6b8a546d49
// flow-typed version: <<STUB>>/cra-build-watch_v^3.0.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cra-build-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cra-build-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cra-build-watch/bin/cra-build-watch' {
  declare module.exports: any;
}

declare module 'cra-build-watch/scripts/__tests__' {
  declare module.exports: any;
}

declare module 'cra-build-watch/scripts' {
  declare module.exports: any;
}

declare module 'cra-build-watch/utils/cliHandler' {
  declare module.exports: any;
}

declare module 'cra-build-watch/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cra-build-watch/bin/cra-build-watch.js' {
  declare module.exports: $Exports<'cra-build-watch/bin/cra-build-watch'>;
}
declare module 'cra-build-watch/scripts/__tests__/index' {
  declare module.exports: $Exports<'cra-build-watch/scripts/__tests__'>;
}
declare module 'cra-build-watch/scripts/__tests__/index.js' {
  declare module.exports: $Exports<'cra-build-watch/scripts/__tests__'>;
}
declare module 'cra-build-watch/scripts/index' {
  declare module.exports: $Exports<'cra-build-watch/scripts'>;
}
declare module 'cra-build-watch/scripts/index.js' {
  declare module.exports: $Exports<'cra-build-watch/scripts'>;
}
declare module 'cra-build-watch/utils/cliHandler.js' {
  declare module.exports: $Exports<'cra-build-watch/utils/cliHandler'>;
}
declare module 'cra-build-watch/utils/index' {
  declare module.exports: $Exports<'cra-build-watch/utils'>;
}
declare module 'cra-build-watch/utils/index.js' {
  declare module.exports: $Exports<'cra-build-watch/utils'>;
}
