// flow-typed signature: 49603a62b312003e9c8ca10353d162fa
// flow-typed version: <<STUB>>/react-dnd_v^10.0.2/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd/dist/cjs/common/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/common/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/internal/drag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/internal/drop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/internal/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/internal/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/internal/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/internal/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/interfaces/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/interfaces/hooksApi' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/interfaces/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/interfaces/options' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/utils/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/cjs/utils/js_utils' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/common/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/internal/drag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/internal/drop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/internal/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/internal/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/internal/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/internal/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/interfaces/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/interfaces/hooksApi' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/interfaces/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/interfaces/options' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/utils/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/esm/utils/js_utils' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/umd/ReactDnD' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/umd/ReactDnD.min' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/drag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/drop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useIsomorphicLayoutEffect' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/hooksApi' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/options' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/js_utils' {
  declare module.exports: any;
}

declare module 'react-dnd/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd/dist/cjs/common/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/DndContext'>;
}
declare module 'react-dnd/dist/cjs/common/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/DndProvider'>;
}
declare module 'react-dnd/dist/cjs/common/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/DragPreviewImage'>;
}
declare module 'react-dnd/dist/cjs/common/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/dist/cjs/common/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/dist/cjs/common/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common'>;
}
declare module 'react-dnd/dist/cjs/common/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common'>;
}
declare module 'react-dnd/dist/cjs/common/registration.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/registration'>;
}
declare module 'react-dnd/dist/cjs/common/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/SourceConnector'>;
}
declare module 'react-dnd/dist/cjs/common/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/TargetConnector'>;
}
declare module 'react-dnd/dist/cjs/common/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/common/wrapConnectorHooks'>;
}
declare module 'react-dnd/dist/cjs/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/createSourceFactory'>;
}
declare module 'react-dnd/dist/cjs/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/createTargetFactory'>;
}
declare module 'react-dnd/dist/cjs/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/decorateHandler'>;
}
declare module 'react-dnd/dist/cjs/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/disposables'>;
}
declare module 'react-dnd/dist/cjs/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/DragLayer'>;
}
declare module 'react-dnd/dist/cjs/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/DragSource'>;
}
declare module 'react-dnd/dist/cjs/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/DropTarget'>;
}
declare module 'react-dnd/dist/cjs/decorators/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators'>;
}
declare module 'react-dnd/dist/cjs/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators'>;
}
declare module 'react-dnd/dist/cjs/decorators/interfaces.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/interfaces'>;
}
declare module 'react-dnd/dist/cjs/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/decorators/utils'>;
}
declare module 'react-dnd/dist/cjs/hooks/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks'>;
}
declare module 'react-dnd/dist/cjs/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks'>;
}
declare module 'react-dnd/dist/cjs/hooks/internal/drag.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/internal/drag'>;
}
declare module 'react-dnd/dist/cjs/hooks/internal/drop.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/internal/drop'>;
}
declare module 'react-dnd/dist/cjs/hooks/internal/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/internal/useCollector'>;
}
declare module 'react-dnd/dist/cjs/hooks/internal/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/internal/useDragDropManager'>;
}
declare module 'react-dnd/dist/cjs/hooks/internal/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/internal/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/dist/cjs/hooks/internal/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/internal/useMonitorOutput'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrag'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDragLayer'>;
}
declare module 'react-dnd/dist/cjs/hooks/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/hooks/useDrop'>;
}
declare module 'react-dnd/dist/cjs/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs'>;
}
declare module 'react-dnd/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs'>;
}
declare module 'react-dnd/dist/cjs/interfaces/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/interfaces/connectors'>;
}
declare module 'react-dnd/dist/cjs/interfaces/hooksApi.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/interfaces/hooksApi'>;
}
declare module 'react-dnd/dist/cjs/interfaces/index' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/interfaces'>;
}
declare module 'react-dnd/dist/cjs/interfaces/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/interfaces'>;
}
declare module 'react-dnd/dist/cjs/interfaces/monitors.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/interfaces/monitors'>;
}
declare module 'react-dnd/dist/cjs/interfaces/options.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/interfaces/options'>;
}
declare module 'react-dnd/dist/cjs/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/utils/cloneWithRef'>;
}
declare module 'react-dnd/dist/cjs/utils/isRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/utils/isRef'>;
}
declare module 'react-dnd/dist/cjs/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/utils/isValidType'>;
}
declare module 'react-dnd/dist/cjs/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd/dist/cjs/utils/js_utils'>;
}
declare module 'react-dnd/dist/esm/common/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/DndContext'>;
}
declare module 'react-dnd/dist/esm/common/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/DndProvider'>;
}
declare module 'react-dnd/dist/esm/common/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/DragPreviewImage'>;
}
declare module 'react-dnd/dist/esm/common/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/dist/esm/common/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/dist/esm/common/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common'>;
}
declare module 'react-dnd/dist/esm/common/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common'>;
}
declare module 'react-dnd/dist/esm/common/registration.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/registration'>;
}
declare module 'react-dnd/dist/esm/common/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/SourceConnector'>;
}
declare module 'react-dnd/dist/esm/common/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/TargetConnector'>;
}
declare module 'react-dnd/dist/esm/common/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/common/wrapConnectorHooks'>;
}
declare module 'react-dnd/dist/esm/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/createSourceFactory'>;
}
declare module 'react-dnd/dist/esm/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/createTargetFactory'>;
}
declare module 'react-dnd/dist/esm/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/decorateHandler'>;
}
declare module 'react-dnd/dist/esm/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/disposables'>;
}
declare module 'react-dnd/dist/esm/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/DragLayer'>;
}
declare module 'react-dnd/dist/esm/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/DragSource'>;
}
declare module 'react-dnd/dist/esm/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/DropTarget'>;
}
declare module 'react-dnd/dist/esm/decorators/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators'>;
}
declare module 'react-dnd/dist/esm/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators'>;
}
declare module 'react-dnd/dist/esm/decorators/interfaces.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/interfaces'>;
}
declare module 'react-dnd/dist/esm/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/decorators/utils'>;
}
declare module 'react-dnd/dist/esm/hooks/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks'>;
}
declare module 'react-dnd/dist/esm/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks'>;
}
declare module 'react-dnd/dist/esm/hooks/internal/drag.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/internal/drag'>;
}
declare module 'react-dnd/dist/esm/hooks/internal/drop.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/internal/drop'>;
}
declare module 'react-dnd/dist/esm/hooks/internal/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/internal/useCollector'>;
}
declare module 'react-dnd/dist/esm/hooks/internal/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/internal/useDragDropManager'>;
}
declare module 'react-dnd/dist/esm/hooks/internal/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/internal/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/dist/esm/hooks/internal/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/internal/useMonitorOutput'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrag'>;
}
declare module 'react-dnd/dist/esm/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDragLayer'>;
}
declare module 'react-dnd/dist/esm/hooks/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/hooks/useDrop'>;
}
declare module 'react-dnd/dist/esm/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm'>;
}
declare module 'react-dnd/dist/esm/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm'>;
}
declare module 'react-dnd/dist/esm/interfaces/connectors.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/interfaces/connectors'>;
}
declare module 'react-dnd/dist/esm/interfaces/hooksApi.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/interfaces/hooksApi'>;
}
declare module 'react-dnd/dist/esm/interfaces/index' {
  declare module.exports: $Exports<'react-dnd/dist/esm/interfaces'>;
}
declare module 'react-dnd/dist/esm/interfaces/index.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/interfaces'>;
}
declare module 'react-dnd/dist/esm/interfaces/monitors.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/interfaces/monitors'>;
}
declare module 'react-dnd/dist/esm/interfaces/options.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/interfaces/options'>;
}
declare module 'react-dnd/dist/esm/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/utils/cloneWithRef'>;
}
declare module 'react-dnd/dist/esm/utils/isRef.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/utils/isRef'>;
}
declare module 'react-dnd/dist/esm/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/utils/isValidType'>;
}
declare module 'react-dnd/dist/esm/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd/dist/esm/utils/js_utils'>;
}
declare module 'react-dnd/dist/umd/ReactDnD.js' {
  declare module.exports: $Exports<'react-dnd/dist/umd/ReactDnD'>;
}
declare module 'react-dnd/dist/umd/ReactDnD.min.js' {
  declare module.exports: $Exports<'react-dnd/dist/umd/ReactDnD.min'>;
}
declare module 'react-dnd/lib/common/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DndContext'>;
}
declare module 'react-dnd/lib/common/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DndProvider'>;
}
declare module 'react-dnd/lib/common/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DragPreviewImage'>;
}
declare module 'react-dnd/lib/common/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/lib/common/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/lib/common/index' {
  declare module.exports: $Exports<'react-dnd/lib/common'>;
}
declare module 'react-dnd/lib/common/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/common'>;
}
declare module 'react-dnd/lib/common/registration.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/registration'>;
}
declare module 'react-dnd/lib/common/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/SourceConnector'>;
}
declare module 'react-dnd/lib/common/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/TargetConnector'>;
}
declare module 'react-dnd/lib/common/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/wrapConnectorHooks'>;
}
declare module 'react-dnd/lib/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/createSourceFactory'>;
}
declare module 'react-dnd/lib/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/createTargetFactory'>;
}
declare module 'react-dnd/lib/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/decorateHandler'>;
}
declare module 'react-dnd/lib/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/disposables'>;
}
declare module 'react-dnd/lib/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragLayer'>;
}
declare module 'react-dnd/lib/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragSource'>;
}
declare module 'react-dnd/lib/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DropTarget'>;
}
declare module 'react-dnd/lib/decorators/index' {
  declare module.exports: $Exports<'react-dnd/lib/decorators'>;
}
declare module 'react-dnd/lib/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators'>;
}
declare module 'react-dnd/lib/decorators/interfaces.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/interfaces'>;
}
declare module 'react-dnd/lib/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/utils'>;
}
declare module 'react-dnd/lib/hooks/index' {
  declare module.exports: $Exports<'react-dnd/lib/hooks'>;
}
declare module 'react-dnd/lib/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks'>;
}
declare module 'react-dnd/lib/hooks/internal/drag.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/drag'>;
}
declare module 'react-dnd/lib/hooks/internal/drop.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/drop'>;
}
declare module 'react-dnd/lib/hooks/internal/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useCollector'>;
}
declare module 'react-dnd/lib/hooks/internal/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useDragDropManager'>;
}
declare module 'react-dnd/lib/hooks/internal/useIsomorphicLayoutEffect.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useIsomorphicLayoutEffect'>;
}
declare module 'react-dnd/lib/hooks/internal/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useMonitorOutput'>;
}
declare module 'react-dnd/lib/hooks/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag'>;
}
declare module 'react-dnd/lib/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDragLayer'>;
}
declare module 'react-dnd/lib/hooks/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop'>;
}
declare module 'react-dnd/lib/index' {
  declare module.exports: $Exports<'react-dnd/lib'>;
}
declare module 'react-dnd/lib/index.js' {
  declare module.exports: $Exports<'react-dnd/lib'>;
}
declare module 'react-dnd/lib/interfaces/connectors.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/connectors'>;
}
declare module 'react-dnd/lib/interfaces/hooksApi.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/hooksApi'>;
}
declare module 'react-dnd/lib/interfaces/index' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces'>;
}
declare module 'react-dnd/lib/interfaces/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces'>;
}
declare module 'react-dnd/lib/interfaces/monitors.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/monitors'>;
}
declare module 'react-dnd/lib/interfaces/options.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/options'>;
}
declare module 'react-dnd/lib/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/cloneWithRef'>;
}
declare module 'react-dnd/lib/utils/isRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/isRef'>;
}
declare module 'react-dnd/lib/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/isValidType'>;
}
declare module 'react-dnd/lib/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/js_utils'>;
}
declare module 'react-dnd/rollup.config.js' {
  declare module.exports: $Exports<'react-dnd/rollup.config'>;
}
